sudo: required
services:
 - docker
language: python
python:
 - "3.5"
install:
 - pip install -r requirements.txt
script:
 - python -m pytest -v
after_success:
 - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
 - export APP=test
 - echo $APP
 - export REPO=$DOCKER_USER/$APP
 - echo $REPO
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 - echo $TAG
 - docker build -f Dockerfile -t $REPO .
 - docker tag $REPO $REPO:$COMMIT
 - docker tag $REPO $REPO:$TAG
 - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
 - docker push $REPO
