sudo: required
services:
 - docker
language: python
python:
 - "3.5"
install:
 - pip install -r requirements.txt
script:
 - python -m pytest -v
after_success:
 - echo "$DOCKER_PASS" | docker login -u "DOCKER_USER" --password-stdin
 - export REPO=ajdurbin/test
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 - docker build -f Dockerfile -t $REPO:$COMMIT .
 - docker tag $REPO:$COMMIT $REPO:$TAG
 - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
 - docker push $REPO
